version: "3.8"

services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - redis
  #     - mongodb
  redis:
    image: redis
    ports:
      - "6378:6379"
  mongodb:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
